# Merges the declarations every unit of the library wrote (ceresc --emit-decls) into the one file all of them import
# and a program takes with --decls: what ceresc writes when it compiles the whole library at once.
#
#   cmake -DLIST=<file listing the units' .decls.casm, one a line> -DOUT=<libceres.decls.casm> -P merge_decls.cmake
#
# A name is declared once. One that a unit declares in @data - a global it uses and another defines - stays in @data
# even when the unit that defines it puts it in @bss (zero-initialized), as ceresc does. The output is only
# rewritten when it changes, so the units that import it are not reassembled for nothing.

file(STRINGS "${LIST}" units)
set(sections data bss rodata text)
foreach(section IN LISTS sections)
    set(order_${section} "")
endforeach()
set(names "")

foreach(unit IN LISTS units)
    if(unit STREQUAL "")
        continue()
    endif()
    file(STRINGS "${unit}" lines)
    set(section "")
    foreach(line IN LISTS lines)
        if(line MATCHES "^@([a-z]+)")
            set(section "${CMAKE_MATCH_1}")
            if(NOT section IN_LIST sections)
                message(FATAL_ERROR "${unit}: a section this does not know: @${section}")
            endif()
            continue()
        endif()
        if(NOT line MATCHES "^global (let )?([A-Za-z_][A-Za-z0-9_]*)")
            continue()
        endif()
        set(name "${CMAKE_MATCH_2}")
        if(NOT DEFINED where_${name})
            set(where_${name} "${section}")
            set(line_${name} "${line}")
            list(APPEND order_${section} "${name}")
        elseif(section STREQUAL "data" AND NOT where_${name} STREQUAL "data")
            list(REMOVE_ITEM order_${where_${name}} "${name}")
            list(APPEND order_data "${name}")
            set(where_${name} "data")
        endif()
    endforeach()
endforeach()

set(text "// Generated by ceresc. Declarations only - no code and no storage.
//
// Every .casm this build generates imports this file, which is what lets one unit name a
// function or a global another one defines. A hand-written .casm can import it too, to call
// into the C side; see docs/07-CASM-Interop.md.
")
foreach(section IN LISTS sections)
    if(NOT order_${section})
        continue()
    endif()
    string(APPEND text "\n@${section}\n")
    foreach(name IN LISTS order_${section})
        string(APPEND text "${line_${name}}\n")
    endforeach()
endforeach()

if(EXISTS "${OUT}")
    file(READ "${OUT}" old)
    if(old STREQUAL text)
        return()
    endif()
endif()
file(WRITE "${OUT}" "${text}")
