// Generates the constant tables that the C sources include: the quarter-wave sine of ceres/fixed.h
// and the CRC-32 table of ceres/hash.h. The output is in the repository; node is only needed to change
// it.   node tools/gen_tables.js
const fs = require("fs");
const path = require("path");
const out = path.join(__dirname, "..", "src", "ceres");

// The C subset rejects a trailing comma in an initializer list, so the last row has none.
function rows(values, perRow, fmt) {
    const lines = [];
    for (let i = 0; i < values.length; i += perRow)
        lines.push("    " + values.slice(i, i + perRow).map(fmt).join(", "));
    return lines.join(",\n");
}

// sin(2*pi*i/256) in 16.16, for i = 0..64: one quarter wave and its endpoint. Round to nearest.
const sin = [];
for (let i = 0; i <= 64; i++) sin.push(Math.round(Math.sin((2 * Math.PI * i) / 256) * 65536));
fs.writeFileSync(path.join(out, "fixed_sin.inc"),
    "// Generated by tools/gen_tables.js: sin(2*pi*i/256) as 16.16, i = 0..64. Do not edit.\n" +
    "static const int fx_sin_quarter[65] = {\n" + rows(sin, 8, (v) => String(v)) + "\n};\n");

// CRC-32 (IEEE 802.3, reflected, polynomial 0xEDB88320).
const crc = [];
for (let n = 0; n < 256; n++) {
    let c = n;
    for (let k = 0; k < 8; k++) c = c & 1 ? (0xEDB88320 ^ (c >>> 1)) >>> 0 : c >>> 1;
    crc.push(c >>> 0);
}
fs.writeFileSync(path.join(out, "hash_crc.inc"),
    "// Generated by tools/gen_tables.js: the CRC-32 table (reflected, polynomial 0xEDB88320). Do not edit.\n" +
    "static const unsigned int crc32_table[256] = {\n" +
    rows(crc, 6, (v) => "0x" + v.toString(16).toUpperCase().padStart(8, "0") + "u") + "\n};\n");
console.log("wrote fixed_sin.inc and hash_crc.inc");
