// Generates tests/f64_vectors.inc (node tools/gen_f64_vectors.js tests/f64_vectors.inc): operands and results for
// test_f64.c. Node's numbers are IEEE binary64 rounded to nearest-even, so what it computes is what the soft
// double must give, bit for bit. The operands come from a fixed seed: the file only changes when this does.
const fs = require("fs");
const out = process.argv[2];

let seed = 0x9E3779B97F4A7C15n;
function next64() {                                   // xorshift64*
    seed ^= seed >> 12n; seed ^= (seed << 25n) & 0xFFFFFFFFFFFFFFFFn; seed ^= seed >> 27n;
    return (seed * 0x2545F4914F6CDD1Dn) & 0xFFFFFFFFFFFFFFFFn;
}
const buf = new DataView(new ArrayBuffer(8));
const bitsOf = (x) => { buf.setFloat64(0, x); return buf.getBigUint64(0); };
const fromBits = (b) => { buf.setBigUint64(0, b); return buf.getFloat64(0); };
const f32Bits = (x) => { buf.setFloat32(0, x); return buf.getUint32(0); };

const specials = [0, -0, 1, -1, 2, 0.5, 3, 0.1, -0.1, 1e308, -1e308, 1.7976931348623157e308, 5e-324, -5e-324,
    2.2250738585072014e-308, 2.225073858507201e-308, Infinity, -Infinity, NaN, 1 / 3, Math.PI, 1e-300, 4503599627370496.5,
    9007199254740993, 0.49999999999999994, 1.0000000000000002, 0.9999999999999999];

// A random double: mostly a spread of exponents, some near 1, some subnormal, some special.
function operand() {
    const r = Number(next64() % 100n);
    if (r < 10) return specials[Number(next64() % BigInt(specials.length))];
    const b = next64();
    if (r < 20) return fromBits(b & 0x800FFFFFFFFFFFFFn);                        // subnormal
    if (r < 55) return fromBits((b & 0x800FFFFFFFFFFFFFn) | (BigInt(1023 - 30 + Number(next64() % 60n)) << 52n));  // near 1
    const e = next64() % 2047n;
    return fromBits((b & 0x800FFFFFFFFFFFFFn) | (e << 52n));
}
// Pairs that cancel, or round on a tie.
function pair() {
    const r = Number(next64() % 10n);
    const a = operand();
    if (r < 2 && isFinite(a) && a !== 0) {
        const b = fromBits(bitsOf(a) ^ (next64() & 0xFn));                     // a few ulps away: cancellation
        return [a, -b];
    }
    return [a, operand()];
}

const hex = (b) => "0x" + b.toString(16).toUpperCase().padStart(16, "0") + "ull";
let text = "// Generated by tools/gen_f64_vectors.js: binary64 operands and node's results. Do not edit by hand.\n";
function table(name, rows, width) {
    text += `#define ${name.toUpperCase()}_COUNT ${rows.length}\n`;
    text += `static const unsigned long long ${name}[${rows.length}][${width}] = {\n`;
    text += rows.map((r) => "    { " + r.map(hex).join(", ") + " }").join(",\n") + "\n};\n";
}

const N = 400;
for (const [name, fn] of [["v_add", (a, b) => a + b], ["v_sub", (a, b) => a - b], ["v_mul", (a, b) => a * b], ["v_div", (a, b) => a / b]]) {
    const rows = [];
    for (let i = 0; i < N; i++) {
        const [a, b] = pair();
        rows.push([bitsOf(a), bitsOf(b), bitsOf(fn(a, b))]);
    }
    table(name, rows, 3);
}
{
    const rows = [];
    for (let i = 0; i < N; i++) { const a = Math.abs(operand()) * (i % 20 === 0 ? -1 : 1); rows.push([bitsOf(a), bitsOf(Math.sqrt(a))]); }
    table("v_sqrt", rows, 2);
}
{
    const rows = [];
    for (let i = 0; i < N; i++) {
        const [a, b] = i % 7 === 0 ? [operand(), -0] : pair();
        const c = Number.isNaN(a) || Number.isNaN(b) ? 2 : a < b ? -1 : a > b ? 1 : 0;
        rows.push([bitsOf(a), bitsOf(b), BigInt.asUintN(64, BigInt(c))]);
    }
    table("v_cmp", rows, 3);
}
{
    // double -> float, rounded; and back, exactly (the float as its bits).
    const rows = [];
    for (let i = 0; i < N; i++) {
        let a = operand();
        if (i % 3 === 0) a = fromBits((next64() & 0x800FFFFFFFFFFFFFn) | (BigInt(1023 - 150 + Number(next64() % 280n)) << 52n));   // float range
        rows.push([bitsOf(a), BigInt(f32Bits(Math.fround(a)))]);
    }
    table("v_to_f32", rows, 2);
}
{
    const rows = [];
    for (let i = 0; i < N; i++) {
        const b = Number(next64() & 0xFFFFFFFFn);
        buf.setUint32(0, b);
        const f = buf.getFloat32(0);
        rows.push([BigInt(b), bitsOf(f)]);
    }
    table("v_from_f32", rows, 2);
}
{
    // 64-bit integers to double (rounded) and doubles to 64-bit integers (truncated, clamped).
    const rows = [];
    for (let i = 0; i < N; i++) {
        let v = next64();
        if (i % 4 === 1) v = v >> BigInt(Number(next64() % 64n));
        const signed = BigInt.asIntN(64, v);
        rows.push([v, bitsOf(Number(signed)), bitsOf(Number(v))]);
    }
    table("v_from_int", rows, 3);
    const rows2 = [];
    for (let i = 0; i < N; i++) {
        let a = operand();
        if (i % 2 === 0) a = fromBits((next64() & 0x800FFFFFFFFFFFFFn) | (BigInt(1023 - 5 + Number(next64() % 75n)) << 52n));
        const clamp = (x, lo, hi) => (x < lo ? lo : x > hi ? hi : x);
        let s, u;
        if (Number.isNaN(a)) { s = 0n; u = 0n; }
        else {
            const t = Math.trunc(a);
            const big = isFinite(t) ? BigInt(t) : t > 0 ? 1n << 70n : -(1n << 70n);
            s = clamp(big, -(1n << 63n), (1n << 63n) - 1n);
            u = a < 0 ? 0n : clamp(big, 0n, (1n << 64n) - 1n);
        }
        rows2.push([bitsOf(a), BigInt.asUintN(64, s), u]);
    }
    table("v_to_int", rows2, 3);
}
fs.writeFileSync(out, text);
console.log("wrote", out, text.length, "bytes");
