// Generates tests/math64_tables.inc (node tools/gen_math64_tables.js tests/math64_tables.inc): reference values for
// test_math64.c, node's own Math.* on each double input. The table holds bit patterns, so neither side is read
// through a decimal. The output is committed, so node is only needed to change the sample points.
//
// node's functions are within about an ulp of the truth themselves (V8 carries fdlibm), so the test allows its own
// few ulps plus theirs. erf, erfc, tgamma and lgamma are not in Math: test_math64.c checks them against values
// worked out to 100 digits instead.
const fs = require("fs");
const out = process.argv[2];

const bits = (x) => {
  const b = Buffer.alloc(8);
  b.writeDoubleLE(x);
  return "0x" + b.readBigUInt64LE().toString(16).toUpperCase().padStart(16, "0") + "ull";
};

const one = {
  sin: [-1e22, -6000, -100, -10, -7, -Math.PI, -1, -0.5, -1e-10, 1e-10, 1e-3, 0.1, 0.5, Math.PI / 4, 1, 1.5, Math.PI / 2, 2, 3,
    Math.PI, 4, 5, 6, 2 * Math.PI, 10, 100, 1000, 12345.678, 823549.6, 1e6, 31415926, 1e10, 1e15, 1e20, 1e22, 1e100, 1e200, 1.7976931348623157e308],
  cos: [-1e22, -6000, -100, -10, -7, -Math.PI, -1, -0.5, -1e-10, 1e-10, 1e-3, 0.1, 0.5, Math.PI / 4, 1, 1.5, Math.PI / 2, 2, 3,
    Math.PI, 4, 5, 6, 2 * Math.PI, 10, 100, 1000, 12345.678, 823549.6, 1e6, 31415926, 1e10, 1e15, 1e20, 1e22, 1e100, 1e200, 1.7976931348623157e308],
  tan: [-1000, -10, -3, -1.5, -1, -0.5, -1e-9, 1e-3, 0.1, 0.5, Math.PI / 4, 1, 1.5, Math.PI / 2, 2, 3, Math.PI, 4, 10, 100, 1e5, 1e10, 1e22, 1e300],
  asin: [-1, -0.99, -0.9, -0.5, -0.1, -1e-10, 1e-10, 0.1, 0.3, 0.5, 0.7071067811865476, 0.9, 0.975, 0.99, 0.9999999, 1],
  acos: [-1, -0.99, -0.9, -0.5, -0.1, -1e-10, 0, 1e-10, 0.1, 0.3, 0.5, 0.7071067811865476, 0.9, 0.99, 0.9999999, 1],
  atan: [-1e20, -1e6, -100, -10, -2, -1, -0.5, -0.1, -1e-10, 1e-10, 0.1, 0.4375, 0.5, 0.6875, 1, 1.1875, 1.5, 2.4375, 10, 1e6, 1e20],
  exp: [-745, -709, -100, -20, -1, -0.5, -0.1, -1e-10, 1e-10, 0.1, 0.34657359, 0.5, 1, 2, 5, 10, 20, 100, 500, 709, 709.78],
  exp2: [-1074, -1022.5, -100, -10, -1.5, -0.5, -0.1, 0.1, 0.5, 1.5, 3, 10, 30.25, 100, 1023, 1023.9],
  expm1: [-40, -10, -1, -0.5, -0.3, -1e-3, -1e-9, 1e-12, 1e-9, 1e-3, 0.1, 0.3, 0.5, 0.9, 1, 2, 5, 20, 700],
  log: [5e-324, 1e-310, 1e-300, 1e-10, 1e-3, 0.1, 0.5, 0.9, 0.9999999999, 1.0000000001, 1.5, 2, Math.E, 10, 100, 12345.678, 1e10, 1e100, 1e300, 1.7976931348623157e308],
  log2: [5e-324, 1e-300, 1e-10, 0.1, 0.5, 0.9, 1.0000000001, 1.5, 2, 3, 8, 10, 1000, 1e10, 1e300],
  log10: [5e-324, 1e-300, 1e-10, 0.001, 0.1, 0.5, 0.9, 1.0000000001, 2, 10, 100, 1000, 12345.678, 1e10, 1e22, 1e300],
  log1p: [-0.999, -0.5, -0.1, -1e-3, -1e-10, 1e-15, 1e-10, 1e-5, 1e-3, 0.1, 0.25, 0.5, 1, 10, 1e10, 1e300],
  sinh: [-700, -20, -5, -1, -0.5, -1e-3, 1e-10, 0.1, 0.5, 0.9, 1, 2, 5, 10, 22, 50, 700, 710],
  cosh: [-700, -20, -5, -1, -0.5, -1e-3, 1e-10, 0.1, 0.3, 0.5, 1, 2, 5, 10, 22, 50, 700, 710],
  tanh: [-20, -8, -2, -1, -0.5, -1e-3, 1e-10, 0.1, 0.5, 0.9, 1, 2, 5, 8, 21.9],
  asinh: [-1e300, -1e10, -100, -10, -1, -0.1, -1e-10, 1e-10, 0.01, 0.5, 1, 2, 10, 100, 1e10, 1e300],
  acosh: [1, 1.0000001, 1.5, 2, 2.5, 5, 10, 100, 1e5, 1e10, 1e300],
  atanh: [-0.9999999, -0.9, -0.5, -0.1, -1e-10, 1e-10, 0.01, 0.1, 0.25, 0.5, 0.75, 0.9, 0.9999999],
  cbrt: [-1e300, -27, -8, -1, -0.001, -1e-310, 1e-310, 1e-300, 0.001, 0.125, 1, 2, 3, 8, 27, 1000, 1e300],
};

const two = {
  pow: [[2, 0.5], [2, 10], [2, -1074], [2, 1023], [10, 22], [10, -5], [0.5, 1000], [1.0000001, 1e9], [0.9999999, -1e9],
    [3, 0.33333333333333333], [1.5, 1.5], [7, -3], [-2, 3], [-2, -3], [-8, 2], [1e-300, 0.5], [1e300, 1.01],
    [12345.678, 12.5], [0.001, -60], [2.718281828459045, 709.7]],
  atan2: [[1, 1], [1, -1], [-1, -1], [-1, 1], [0.5, 1e10], [1e10, 0.5], [3, 4], [-3, 4], [1e-300, 1], [1, 1e-300], [2, -1e-5], [-7, -9]],
  hypot: [[3, 4], [5, 12], [1e300, 1e300], [1e-300, 1e-300], [1, 1e-10], [1e200, 3], [-8, 15], [0.1, 0.2]],
};

let s = "// Generated by tools/gen_math64_tables.js: double inputs and node's Math.* on them, as bit patterns. Do not edit by hand.\n";
for (const [name, xs] of Object.entries(one)) {
  const fn = name === "exp2" ? (x) => Math.pow(2, x) : Math[name];
  s += `static const unsigned long long t64_${name}[${xs.length}][2] = {\n`;
  for (const x of xs) s += `    { ${bits(x)}, ${bits(fn(x))} },\n`;
  s += "};\n";
}
for (const [name, ps] of Object.entries(two)) {
  s += `static const unsigned long long t64_${name}[${ps.length}][3] = {\n`;
  for (const [a, b] of ps) s += `    { ${bits(a)}, ${bits(b)}, ${bits(Math[name](a, b))} },\n`;
  s += "};\n";
}
fs.writeFileSync(out, s);
